#!/bin/sh
#-
# Copyright (c) 2011 Nathan Whitehorn
# Copyright (c) 2013-2015 Devin Teske
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
#
############################################################ MAIN

#cat $BSDINSTALL_TMPETC/rc.conf.* >> $BSDINSTALL_TMPETC/rc.conf
#rm $BSDINSTALL_TMPETC/rc.conf.*

cat $BSDINSTALL_CHROOT/etc/sysctl.conf $BSDINSTALL_TMPETC/sysctl.conf.* >> $BSDINSTALL_TMPETC/sysctl.conf
rm $BSDINSTALL_TMPETC/sysctl.conf*

if [ -f $BSDINSTALL_TMPETC/ttys.hardening ]; then
	cat $BSDINSTALL_TMPETC/ttys.hardening > $BSDINSTALL_TMPETC/ttys
	rm $BSDINSTALL_TMPETC/ttys.hardening
fi

cp $BSDINSTALL_TMPETC/* $BSDINSTALL_CHROOT/etc

# Copy pfSense loader.conf
if [ -f $BSDINSTALL_CHROOT/boot/loader.conf ]; then
	if [ ! -f "$BSDINSTALL_TMPBOOT/loader.conf" ]; then
		touch $BSDINSTALL_TMPBOOT/loader.conf
	fi
	cat $BSDINSTALL_CHROOT/boot/loader.conf $BSDINSTALL_TMPBOOT/loader.conf \
	    | sort -u > $BSDINSTALL_TMPBOOT/loader.conf.tmp
	mv $BSDINSTALL_TMPBOOT/loader.conf.tmp $BSDINSTALL_TMPBOOT/loader.conf

	cp $BSDINSTALL_CHROOT/boot/loader.conf \
	    $BSDINSTALL_TMPBOOT/loader.conf.pfSense
fi

cat $BSDINSTALL_TMPBOOT/loader.conf.* >> $BSDINSTALL_TMPBOOT/loader.conf
rm $BSDINSTALL_TMPBOOT/loader.conf.*
df -t zfs $BSDINSTALL_CHROOT > /dev/null && echo "zfs_load=\"YES\"" >> $BSDINSTALL_TMPBOOT/loader.conf

# Detect MBT-* and populate loader.conf.local
product=$(/bin/kenv -q smbios.system.product 2>/dev/null)

if [ "${product}" = "Minnowboard Turbot D0 PLATFORM" ] || [ "${product}" = "Minnowboard Turbot D0/D1 PLATFORM" ]; then
	echo "i915kms_load=YES" >> $BSDINSTALL_TMPBOOT/loader.conf.local
	echo "drm.i915.enable_unsupported=1" >> $BSDINSTALL_TMPBOOT/loader.conf.local
	echo "kern.vt.fb.modes.VGA-1=d" >> $BSDINSTALL_TMPBOOT/loader.conf.local
	echo "kern.vt.fb.default_mode=\"1024x768\"" >> $BSDINSTALL_TMPBOOT/loader.conf.local
fi

# Add default values for hn devices to work with ALTQ
# See https://redmine.pfsense.org/issues/8954
echo 'hw.hn.vf_transparent="0"' >> $BSDINSTALL_TMPBOOT/loader.conf
echo 'hw.hn.use_if_start="1"' >> $BSDINSTALL_TMPBOOT/loader.conf

if [ -f /tmp/loader.conf.pfSense ]; then
	cat /tmp/loader.conf.pfSense $BSDINSTALL_TMPBOOT/loader.conf \
	    | sort -u > $BSDINSTALL_TMPBOOT/loader.conf.tmp
	mv $BSDINSTALL_TMPBOOT/loader.conf.tmp $BSDINSTALL_TMPBOOT/loader.conf
fi

if [ -f /tmp/loader.conf.local.pfSense ]; then
	cat /tmp/loader.conf.local.pfSense $BSDINSTALL_TMPBOOT/loader.conf.local \
	    | sort -u > $BSDINSTALL_TMPBOOT/loader.conf.local.tmp
	mv $BSDINSTALL_TMPBOOT/loader.conf.local.tmp $BSDINSTALL_TMPBOOT/loader.conf.local
fi

cp $BSDINSTALL_TMPBOOT/* $BSDINSTALL_CHROOT/boot

if [ -f /tmp/boot.config ]; then
	cp /tmp/boot.conf $BSDINSTALL_CHROOT
fi

[ "${debugFile#+}" ] && cp "${debugFile#+}" $BSDINSTALL_CHROOT/var/log/

# Set up other things from installed config
#chroot $BSDINSTALL_CHROOT /usr/bin/newaliases > /dev/null 2>&1

exit 0

################################################################################
# END
################################################################################
