# $FreeBSD$

SCRIPTS= auto adduser checksum config docsinstall entropy fix_fstab hardening hostname jail \
	 keymap mirrorselect mount netconfig netconfig_ipv4 netconfig_ipv6 \
	 rootpass script services time umount wlanconfig zfsboot copy_configxml_from_usb
BINDIR= ${LIBEXECDIR}/bsdinstall

MAN=

.include <bsd.prog.mk>
